//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loop_Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string CustomerID { get; set; }
        public string Date { get; set; }
        public string Name { get; set; }
        public Nullable<int> OpeningBalance { get; set; }
        public string OpeningBalanceType { get; set; }
        public string Address { get; set; }
        public string EmailID { get; set; }
        public string Phoneno { get; set; }
        public string Mobileno { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string AccountName { get; set; }
        public string Branch { get; set; }
        public string AccountNumber { get; set; }
        public string Remarks { get; set; }
        public string defaultTransaction { get; set; }
        public string DefDiscountPercentage { get; set; }
        public Nullable<decimal> DirectDiscount { get; set; }
        public string NextShopping { get; set; }
        public string PayTerms { get; set; }
        public string CurrencyType { get; set; }
        public string Status { get; set; }
    }
}
