//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loop_Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int id { get; set; }
        public string SupplierID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
        public string AccountNature { get; set; }
        public string CurrencyType { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public string OpeningBalanceType { get; set; }
        public string Address { get; set; }
        public string EmailID { get; set; }
        public string Mobileno { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string AccountName { get; set; }
        public string Branch { get; set; }
        public string AccountNumber { get; set; }
        public string DefultTransaction { get; set; }
        public string Pricinglevel { get; set; }
        public string Status { get; set; }
    }
}
