//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loop_Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AddExpenses
    {
        public int id { get; set; }
        public string Date { get; set; }
        public Nullable<decimal> InvoiceNumber { get; set; }
        public string ExpenseType { get; set; }
        public string ExpensesName { get; set; }
        public string CurrencyType { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Notes { get; set; }
        public string PaymentMethods { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
