//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loop_Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AddRevenue
    {
        public int id { get; set; }
        public Nullable<decimal> RevenueNumber { get; set; }
        public Nullable<decimal> RevenueNumber2 { get; set; }
        public string Date { get; set; }
        public string CurrencyType { get; set; }
        public string RevenueName { get; set; }
        public Nullable<decimal> TotalBeforeTax { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentMethods { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Notes { get; set; }
    }
}
