//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loop_Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccountMaster
    {
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Accounttype { get; set; }
        public string AccountName { get; set; }
        public string SubAccountof { get; set; }
        public string AccountRules { get; set; }
        public string AccountCurrency { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
    }
}
