//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loop_Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBonusQuantity
    {
        public decimal ID { get; set; }
        public string Barcode { get; set; }
        public string ItemName { get; set; }
        public string TypeOfUnit { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> OfferQuantity { get; set; }
        public Nullable<decimal> Bonus { get; set; }
    }
}
