//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loop_Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemMaster
    {
        public decimal ID { get; set; }
        public string Barcode1 { get; set; }
        public string Barcode2 { get; set; }
        public string Code { get; set; }
        public string NameArabic { get; set; }
        public string NameEng { get; set; }
        public string StoreType { get; set; }
        public string BrandName { get; set; }
        public string Category { get; set; }
        public string Unit { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> QtyPerUnit { get; set; }
        public string Company { get; set; }
        public string Vender { get; set; }
        public string DiscountType { get; set; }
        public Nullable<decimal> DirectDiscount { get; set; }
        public Nullable<decimal> NextShoppingDiscount { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<decimal> ReorderLevel { get; set; }
        public Nullable<System.DateTime> ManufacturingDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string PurchaseCurrency { get; set; }
        public string SellingCurrency { get; set; }
        public Nullable<decimal> WholeSalePrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> CustomPrice { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> CustomerPrice { get; set; }
        public Nullable<decimal> AddProfit { get; set; }
        public string Status { get; set; }
    }
}
